name: localization_helper
description: This is command line Dart application that helps in implementing localization in Flutter apps.
version: 1.0.0
repository: https://github.com/rijalsandeshraj/localization_helper

environment:
  sdk: ">=2.18.4 <3.0.0"

executables:
  localization_helper:

dependencies:
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
